// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mktba.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mktba.Infrastructure.Migrations
{
    [DbContext(typeof(MktbaDbContext))]
    [Migration("20260421082223_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mktba.Domain.Entities.AdminInviteToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UsedByUserId");

                    b.ToTable("AdminInviteTokens");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.AiProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("text");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MarkdownStylingSystemPrompt")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("AiProviderSettings");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("InfoboxSubtitle")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("InfoboxTitle")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("ParentArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Tags")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.ArticleInfoboxField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Order");

                    b.ToTable("ArticleInfoboxFields");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.ArticleRelatedLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RelatedArticleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelatedArticleId");

                    b.HasIndex("ArticleId", "Order");

                    b.ToTable("ArticleRelatedLinks");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("ParagraphId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParagraphId");

                    b.ToTable("Opinions");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.OpinionSchool", b =>
                {
                    b.Property<int>("OpinionId")
                        .HasColumnType("integer");

                    b.Property<int>("SchoolId")
                        .HasColumnType("integer");

                    b.HasKey("OpinionId", "SchoolId");

                    b.HasIndex("SchoolId");

                    b.ToTable("OpinionSchools");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId", "Order");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ArticleScopeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleScopeId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.AdminInviteToken", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mktba.Domain.Entities.User", "UsedByUser")
                        .WithMany()
                        .HasForeignKey("UsedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UsedByUser");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Article", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Article", "ParentArticle")
                        .WithMany("ChildArticles")
                        .HasForeignKey("ParentArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentArticle");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.ArticleInfoboxField", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Article", "Article")
                        .WithMany("InfoboxFields")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.ArticleRelatedLink", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Article", "Article")
                        .WithMany("RelatedLinks")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mktba.Domain.Entities.Article", "RelatedArticle")
                        .WithMany()
                        .HasForeignKey("RelatedArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("RelatedArticle");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Opinion", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Paragraph", "Paragraph")
                        .WithMany("Opinions")
                        .HasForeignKey("ParagraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paragraph");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.OpinionSchool", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Opinion", "Opinion")
                        .WithMany("OpinionSchools")
                        .HasForeignKey("OpinionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mktba.Domain.Entities.School", "School")
                        .WithMany("OpinionSchools")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opinion");

                    b.Navigation("School");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Paragraph", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Article", "Article")
                        .WithMany("Paragraphs")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.School", b =>
                {
                    b.HasOne("Mktba.Domain.Entities.Article", "ArticleScope")
                        .WithMany("CustomSchools")
                        .HasForeignKey("ArticleScopeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ArticleScope");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Article", b =>
                {
                    b.Navigation("ChildArticles");

                    b.Navigation("CustomSchools");

                    b.Navigation("InfoboxFields");

                    b.Navigation("Paragraphs");

                    b.Navigation("RelatedLinks");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Opinion", b =>
                {
                    b.Navigation("OpinionSchools");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.Paragraph", b =>
                {
                    b.Navigation("Opinions");
                });

            modelBuilder.Entity("Mktba.Domain.Entities.School", b =>
                {
                    b.Navigation("OpinionSchools");
                });
#pragma warning restore 612, 618
        }
    }
}
